version: '3.8'

services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - ./data/node1:/data/db
      - ./mongodb-keyfile:/tmp/mongodb-keyfile
      - ./init-replica.js:/scripts/init-replica.js
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      bash -c "
      cp /tmp/mongodb-keyfile /data/mongodb-keyfile &&
      chmod 400 /data/mongodb-keyfile &&
      chown 999:999 /data/mongodb-keyfile &&
      exec gosu mongodb mongod --replSet rs0 --port 27018 --bind_ip_all --keyFile /data/mongodb-keyfile --transitionToAuth
      "

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    restart: always
    ports:
      - "27019:27019"
    volumes:
      - ./data/node2:/data/db
      - ./mongodb-keyfile:/tmp/mongodb-keyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      bash -c "
      cp /tmp/mongodb-keyfile /data/mongodb-keyfile &&
      chmod 400 /data/mongodb-keyfile &&
      chown 999:999 /data/mongodb-keyfile &&
      exec gosu mongodb mongod --replSet rs0 --port 27019 --bind_ip_all --keyFile /data/mongodb-keyfile --transitionToAuth
      "

